//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_CHAM_CONG
    {
        public int MaNS { get; set; }
        public Nullable<byte> SoNgayDiLam { get; set; }
        public Nullable<byte> SoNgayNghiCoPhep { get; set; }
        public Nullable<byte> SoNgayNghi { get; set; }
        public byte Thang { get; set; }
        public int Nam { get; set; }
    
        public virtual NHAN_SU NHAN_SU { get; set; }
    }
}
