//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DU_AN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DU_AN()
        {
            this.NHAN_SU1 = new HashSet<NHAN_SU>();
        }
    
        public int MaDA { get; set; }
        public string TenDA { get; set; }
        public Nullable<System.DateTime> TGBD { get; set; }
        public Nullable<System.DateTime> TGHTDK { get; set; }
        public Nullable<byte> SoTV { get; set; }
        public Nullable<int> MaQL { get; set; }
    
        public virtual NHAN_SU NHAN_SU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHAN_SU> NHAN_SU1 { get; set; }
    }
}
