//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_SU_BACKUP
    {
        public int MaNS { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string QueQuan { get; set; }
        public string SDT { get; set; }
        public string TrinhDo { get; set; }
        public string DanToc { get; set; }
        public string ChuyenNganh { get; set; }
        public string QuocTich { get; set; }
        public byte[] Avt { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> MaPB { get; set; }
        public Nullable<int> MaHD { get; set; }
        public Nullable<int> MaCV { get; set; }
    }
}
