//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLNSCon : DbContext
    {
        public QLNSCon()
            : base("name=QLNSCon")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANG_CHAM_CONG> BANG_CHAM_CONG { get; set; }
        public virtual DbSet<CHUC_VU> CHUC_VU { get; set; }
        public virtual DbSet<DU_AN> DU_AN { get; set; }
        public virtual DbSet<HOP_DONG> HOP_DONG { get; set; }
        public virtual DbSet<KHEN_THUONG> KHEN_THUONG { get; set; }
        public virtual DbSet<LUONG> LUONGs { get; set; }
        public virtual DbSet<NHAN_SU> NHAN_SU { get; set; }
        public virtual DbSet<NHAN_SU_BACKUP> NHAN_SU_BACKUP { get; set; }
        public virtual DbSet<PHONG_BAN> PHONG_BAN { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int suaPB(Nullable<int> mapb, string ten, string diachi, string email, string sdt, Nullable<int> matp)
        {
            var mapbParameter = mapb.HasValue ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var matpParameter = matp.HasValue ?
                new ObjectParameter("matp", matp) :
                new ObjectParameter("matp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("suaPB", mapbParameter, tenParameter, diachiParameter, emailParameter, sdtParameter, matpParameter);
        }
    
        public virtual int suaTTNS(Nullable<int> mans, string ten, Nullable<System.DateTime> ngaysinh, Nullable<bool> gioitinh, string quequan, string sDT, string trinhdo, string dantoc, string chuyennganh, string quoctich, string diachi, Nullable<int> mapb, Nullable<int> macv)
        {
            var mansParameter = mans.HasValue ?
                new ObjectParameter("mans", mans) :
                new ObjectParameter("mans", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh.HasValue ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(bool));
    
            var quequanParameter = quequan != null ?
                new ObjectParameter("quequan", quequan) :
                new ObjectParameter("quequan", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var trinhdoParameter = trinhdo != null ?
                new ObjectParameter("trinhdo", trinhdo) :
                new ObjectParameter("trinhdo", typeof(string));
    
            var dantocParameter = dantoc != null ?
                new ObjectParameter("dantoc", dantoc) :
                new ObjectParameter("dantoc", typeof(string));
    
            var chuyennganhParameter = chuyennganh != null ?
                new ObjectParameter("chuyennganh", chuyennganh) :
                new ObjectParameter("chuyennganh", typeof(string));
    
            var quoctichParameter = quoctich != null ?
                new ObjectParameter("quoctich", quoctich) :
                new ObjectParameter("quoctich", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var mapbParameter = mapb.HasValue ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(int));
    
            var macvParameter = macv.HasValue ?
                new ObjectParameter("macv", macv) :
                new ObjectParameter("macv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("suaTTNS", mansParameter, tenParameter, ngaysinhParameter, gioitinhParameter, quequanParameter, sDTParameter, trinhdoParameter, dantocParameter, chuyennganhParameter, quoctichParameter, diachiParameter, mapbParameter, macvParameter);
        }
    
        public virtual int themBCC(Nullable<int> mans, Nullable<byte> thang, Nullable<int> nam, Nullable<byte> sndl, Nullable<byte> snnp, Nullable<byte> snn)
        {
            var mansParameter = mans.HasValue ?
                new ObjectParameter("mans", mans) :
                new ObjectParameter("mans", typeof(int));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(byte));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            var sndlParameter = sndl.HasValue ?
                new ObjectParameter("sndl", sndl) :
                new ObjectParameter("sndl", typeof(byte));
    
            var snnpParameter = snnp.HasValue ?
                new ObjectParameter("snnp", snnp) :
                new ObjectParameter("snnp", typeof(byte));
    
            var snnParameter = snn.HasValue ?
                new ObjectParameter("snn", snn) :
                new ObjectParameter("snn", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themBCC", mansParameter, thangParameter, namParameter, sndlParameter, snnpParameter, snnParameter);
        }
    
        public virtual int themNV(string ten, Nullable<System.DateTime> ngaysinh, Nullable<bool> gioitinh, string quequan, string sdt, string trinhdo, string dantoc, string chuyennganh, string quocgia, string diachi, Nullable<int> mapb, Nullable<int> maCV)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh.HasValue ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(bool));
    
            var quequanParameter = quequan != null ?
                new ObjectParameter("quequan", quequan) :
                new ObjectParameter("quequan", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var trinhdoParameter = trinhdo != null ?
                new ObjectParameter("trinhdo", trinhdo) :
                new ObjectParameter("trinhdo", typeof(string));
    
            var dantocParameter = dantoc != null ?
                new ObjectParameter("dantoc", dantoc) :
                new ObjectParameter("dantoc", typeof(string));
    
            var chuyennganhParameter = chuyennganh != null ?
                new ObjectParameter("chuyennganh", chuyennganh) :
                new ObjectParameter("chuyennganh", typeof(string));
    
            var quocgiaParameter = quocgia != null ?
                new ObjectParameter("quocgia", quocgia) :
                new ObjectParameter("quocgia", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var mapbParameter = mapb.HasValue ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(int));
    
            var maCVParameter = maCV.HasValue ?
                new ObjectParameter("maCV", maCV) :
                new ObjectParameter("maCV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themNV", tenParameter, ngaysinhParameter, gioitinhParameter, quequanParameter, sdtParameter, trinhdoParameter, dantocParameter, chuyennganhParameter, quocgiaParameter, diachiParameter, mapbParameter, maCVParameter);
        }
    
        public virtual int themPB(string ten, string diachi, string email, string sdt, Nullable<int> matp)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var matpParameter = matp.HasValue ?
                new ObjectParameter("matp", matp) :
                new ObjectParameter("matp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themPB", tenParameter, diachiParameter, emailParameter, sdtParameter, matpParameter);
        }
    
        public virtual ObjectResult<xemDSPB_Result> xemDSPB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xemDSPB_Result>("xemDSPB");
        }
    
        public virtual ObjectResult<xemDSTTNS_Result> xemDSTTNS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xemDSTTNS_Result>("xemDSTTNS");
        }
    
        public virtual ObjectResult<xemLuongThang_Result> xemLuongThang(Nullable<byte> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(byte));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xemLuongThang_Result>("xemLuongThang", thangParameter, namParameter);
        }
    
        public virtual int xoaNS(Nullable<int> mans)
        {
            var mansParameter = mans.HasValue ?
                new ObjectParameter("mans", mans) :
                new ObjectParameter("mans", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoaNS", mansParameter);
        }
    
        public virtual int xoaPB(Nullable<int> mapb)
        {
            var mapbParameter = mapb.HasValue ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoaPB", mapbParameter);
        }
    
        public virtual int suaBCC(Nullable<int> mans, Nullable<byte> thang, Nullable<int> nam, Nullable<byte> sndl, Nullable<byte> snnp, Nullable<byte> snn)
        {
            var mansParameter = mans.HasValue ?
                new ObjectParameter("mans", mans) :
                new ObjectParameter("mans", typeof(int));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(byte));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            var sndlParameter = sndl.HasValue ?
                new ObjectParameter("sndl", sndl) :
                new ObjectParameter("sndl", typeof(byte));
    
            var snnpParameter = snnp.HasValue ?
                new ObjectParameter("snnp", snnp) :
                new ObjectParameter("snnp", typeof(byte));
    
            var snnParameter = snn.HasValue ?
                new ObjectParameter("snn", snn) :
                new ObjectParameter("snn", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("suaBCC", mansParameter, thangParameter, namParameter, sndlParameter, snnpParameter, snnParameter);
        }
    
        public virtual int xoaBCC(Nullable<int> mans, Nullable<byte> thang, Nullable<int> nam)
        {
            var mansParameter = mans.HasValue ?
                new ObjectParameter("mans", mans) :
                new ObjectParameter("mans", typeof(int));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(byte));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoaBCC", mansParameter, thangParameter, namParameter);
        }
    
        public virtual int suaDA(Nullable<int> mada, string ten, Nullable<System.DateTime> tGBD, Nullable<System.DateTime> tGHTDK, Nullable<int> maql)
        {
            var madaParameter = mada.HasValue ?
                new ObjectParameter("mada", mada) :
                new ObjectParameter("mada", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var tGBDParameter = tGBD.HasValue ?
                new ObjectParameter("TGBD", tGBD) :
                new ObjectParameter("TGBD", typeof(System.DateTime));
    
            var tGHTDKParameter = tGHTDK.HasValue ?
                new ObjectParameter("TGHTDK", tGHTDK) :
                new ObjectParameter("TGHTDK", typeof(System.DateTime));
    
            var maqlParameter = maql.HasValue ?
                new ObjectParameter("maql", maql) :
                new ObjectParameter("maql", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("suaDA", madaParameter, tenParameter, tGBDParameter, tGHTDKParameter, maqlParameter);
        }
    
        public virtual ObjectResult<xemDSDA_Result> xemDSDA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xemDSDA_Result>("xemDSDA");
        }
    
        public virtual ObjectResult<xemDSNSDA_Result> xemDSNSDA(Nullable<int> mada)
        {
            var madaParameter = mada.HasValue ?
                new ObjectParameter("mada", mada) :
                new ObjectParameter("mada", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xemDSNSDA_Result>("xemDSNSDA", madaParameter);
        }
    
        public virtual int xoaDA(Nullable<int> mada)
        {
            var madaParameter = mada.HasValue ?
                new ObjectParameter("mada", mada) :
                new ObjectParameter("mada", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoaDA", madaParameter);
        }
    
        public virtual int xoaNSDA(Nullable<int> mada, Nullable<int> mans)
        {
            var madaParameter = mada.HasValue ?
                new ObjectParameter("mada", mada) :
                new ObjectParameter("mada", typeof(int));
    
            var mansParameter = mans.HasValue ?
                new ObjectParameter("mans", mans) :
                new ObjectParameter("mans", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoaNSDA", madaParameter, mansParameter);
        }
    
        public virtual int themDA(string ten, Nullable<System.DateTime> tGBD, Nullable<System.DateTime> tGHTDK, Nullable<int> maql)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var tGBDParameter = tGBD.HasValue ?
                new ObjectParameter("TGBD", tGBD) :
                new ObjectParameter("TGBD", typeof(System.DateTime));
    
            var tGHTDKParameter = tGHTDK.HasValue ?
                new ObjectParameter("TGHTDK", tGHTDK) :
                new ObjectParameter("TGHTDK", typeof(System.DateTime));
    
            var maqlParameter = maql.HasValue ?
                new ObjectParameter("maql", maql) :
                new ObjectParameter("maql", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themDA", tenParameter, tGBDParameter, tGHTDKParameter, maqlParameter);
        }
    
        public virtual int themNSDA(Nullable<int> mada, Nullable<int> mans)
        {
            var madaParameter = mada.HasValue ?
                new ObjectParameter("mada", mada) :
                new ObjectParameter("mada", typeof(int));
    
            var mansParameter = mans.HasValue ?
                new ObjectParameter("mans", mans) :
                new ObjectParameter("mans", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themNSDA", madaParameter, mansParameter);
        }
    
        public virtual int suaKT(Nullable<int> makt, string hinhthuc, Nullable<System.DateTime> ngaykt, Nullable<decimal> giatri, string noidung)
        {
            var maktParameter = makt.HasValue ?
                new ObjectParameter("makt", makt) :
                new ObjectParameter("makt", typeof(int));
    
            var hinhthucParameter = hinhthuc != null ?
                new ObjectParameter("hinhthuc", hinhthuc) :
                new ObjectParameter("hinhthuc", typeof(string));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var giatriParameter = giatri.HasValue ?
                new ObjectParameter("giatri", giatri) :
                new ObjectParameter("giatri", typeof(decimal));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("suaKT", maktParameter, hinhthucParameter, ngayktParameter, giatriParameter, noidungParameter);
        }
    
        public virtual int taoKT(string hinhthuc, Nullable<System.DateTime> ngaykt, Nullable<decimal> giatri, string noidung)
        {
            var hinhthucParameter = hinhthuc != null ?
                new ObjectParameter("hinhthuc", hinhthuc) :
                new ObjectParameter("hinhthuc", typeof(string));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            var giatriParameter = giatri.HasValue ?
                new ObjectParameter("giatri", giatri) :
                new ObjectParameter("giatri", typeof(decimal));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("taoKT", hinhthucParameter, ngayktParameter, giatriParameter, noidungParameter);
        }
    
        public virtual int themNSKT(Nullable<int> makt, Nullable<int> mans)
        {
            var maktParameter = makt.HasValue ?
                new ObjectParameter("makt", makt) :
                new ObjectParameter("makt", typeof(int));
    
            var mansParameter = mans.HasValue ?
                new ObjectParameter("mans", mans) :
                new ObjectParameter("mans", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("themNSKT", maktParameter, mansParameter);
        }
    
        public virtual ObjectResult<xemDSKT_Result> xemDSKT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xemDSKT_Result>("xemDSKT");
        }
    
        public virtual ObjectResult<xemNSKT_Result> xemNSKT(Nullable<int> makt)
        {
            var maktParameter = makt.HasValue ?
                new ObjectParameter("makt", makt) :
                new ObjectParameter("makt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xemNSKT_Result>("xemNSKT", maktParameter);
        }
    
        public virtual int xoaKT(Nullable<int> makt)
        {
            var maktParameter = makt.HasValue ?
                new ObjectParameter("makt", makt) :
                new ObjectParameter("makt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoaKT", maktParameter);
        }
    
        public virtual int xoaNSKT(Nullable<int> makt, Nullable<int> mans)
        {
            var maktParameter = makt.HasValue ?
                new ObjectParameter("makt", makt) :
                new ObjectParameter("makt", typeof(int));
    
            var mansParameter = mans.HasValue ?
                new ObjectParameter("mans", mans) :
                new ObjectParameter("mans", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoaNSKT", maktParameter, mansParameter);
        }
    }
}
